---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lufeijun1234.
--- DateTime: 2022/7/25 11:56 AM
---
local typedefs = require "kong.db.schema.typedefs"

return {
    name = "uri-rate",
    fields = {
        { consumer = typedefs.no_consumer  },
        {
            config = {
                type = "record",
                fields = {
                    {
                        allow_uri = { type = "string", required = true },
                    },
                },
            },
        },
    },
}
